# 2. Numpy Package

    คือ Package พื้นฐานสำหรับการคำนวณด้านวิทยาศาสตร์ โดยมีฟังก์ชันเกี่ยวกับคณิตศาสตร์ สามารถคำนวณชุดข้อมูล Array ที่มีขนาดใหญ่และซับซ้อนได้
    
                                                                                    Data Science ง่าย . . by New ew ew

In [1]:
!pip install numpy

  Using cached numpy-1.18.3-cp38-cp38-win_amd64.whl (12.8 MB)

ERROR: seaborn 0.10.1 requires pandas>=0.22.0, which is not installed.


## 1) Numpy Array

In [2]:
# Create numpy array
import numpy as np

oneDim = np.array([1.0,2,3,4,5])   # a 1-dimensional array (vector)
print("oneDim : ",oneDim)
print("#Dimensions =", oneDim.ndim)
print("Dimension =", oneDim.shape)
print("Size =", oneDim.size)
print("Array type =", oneDim.dtype)

twoDim = np.array([[1,2],[3,4],[5,6],[7,8]])  # a two-dimensional array (matrix)
print("twoDim : ",twoDim)
print("#Dimensions =", twoDim.ndim)
print("Dimension =", twoDim.shape)
print("Size =", twoDim.size)
print("Array type =", twoDim.dtype)

arrFromTuple = np.array([(1,'a',3.0),(2,'b',3.5)])  # create ndarray from tuple
print("arrFromTuple : ",arrFromTuple)
print("#Dimensions =", arrFromTuple.ndim)
print("Dimension =", arrFromTuple.shape)
print("Size =", arrFromTuple.size)

oneDim :  [1. 2. 3. 4. 5.]
#Dimensions = 1
Dimension = (5,)
Size = 5
Array type = float64
twoDim :  [[1 2]
 [3 4]
 [5 6]
 [7 8]]
#Dimensions = 2
Dimension = (4, 2)
Size = 8
Array type = int32
arrFromTuple :  [['1' 'a' '3.0']
 ['2' 'b' '3.5']]
#Dimensions = 2
Dimension = (2, 3)
Size = 6


In [3]:
print("np.random.rand(5) : ",np.random.rand(5))      # random numbers from a uniform distribution between [0,1]
print("np.random.randn(5) : ",np.random.randn(5))     # random numbers from a normal distribution
print("np.arange(-10,10,2) : ",np.arange(-10,10,2))    # similar to range, but returns ndarray instead of list
print("np.arange(12).reshape(3,4) : ",np.arange(12).reshape(3,4))  # reshape to a matrix
print("np.linspace(0,1,10) : ",np.linspace(0,1,10))    # split interval [0,1] into 10 equally separated values
print("np.logspace(-3,3,7) : ",np.logspace(-3,3,7))    # create ndarray with values from 10^-3 to 10^3

np.random.rand(5) :  [0.01359692 0.94072369 0.25063937 0.18662095 0.5763899 ]
np.random.randn(5) :  [-0.99058541 -0.54949384 -1.63431857 -0.97371107  1.34424189]
np.arange(-10,10,2) :  [-10  -8  -6  -4  -2   0   2   4   6   8]
np.arange(12).reshape(3,4) :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
np.linspace(0,1,10) :  [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
np.logspace(-3,3,7) :  [1.e-03 1.e-02 1.e-01 1.e+00 1.e+01 1.e+02 1.e+03]


In [4]:
print("np.zeros((2,3)) : ",np.zeros((2,3)))        # a matrix of zeros
print("np.ones((3,2)) : ",np.ones((3,2)))         # a matrix of ones
print("np.eye(3) : ",np.eye(3))              # a 3 x 3 identity matrix

np.zeros((2,3)) :  [[0. 0. 0.]
 [0. 0. 0.]]
np.ones((3,2)) :  [[1. 1.]
 [1. 1.]
 [1. 1.]]
np.eye(3) :  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 2) Element-wise Operations

In [5]:
x = np.array([1,2,3,4,5])

print("x + 1 : ",x + 1)      # addition
print("x - 1 : ",x - 1)      # subtraction
print("x * 2 : ",x * 2)      # multiplication
print("1 / x : ",1 / x)      # division
print("x // 2 : ",x // 2)     # integer division
print("x ** 2 : ",x ** 2)     # square
print("x % 2 : ",x % 2)      # modulo  

x + 1 :  [2 3 4 5 6]
x - 1 :  [0 1 2 3 4]
x * 2 :  [ 2  4  6  8 10]
1 / x :  [1.         0.5        0.33333333 0.25       0.2       ]
x // 2 :  [0 1 1 2 2]
x ** 2 :  [ 1  4  9 16 25]
x % 2 :  [1 0 1 0 1]


In [6]:
x = np.array([2,4,6,8,10])
y = np.array([1,2,3,4,5])

print("x + y : ",x + y)
print("x - y : ",x - y)
print("x * y : ",x * y)
print("x / y : ",x / y)
print("x // y : ",x // y)
print("x ** y : ",x ** y)

x + y :  [ 3  6  9 12 15]
x - y :  [1 2 3 4 5]
x * y :  [ 2  8 18 32 50]
x / y :  [2. 2. 2. 2. 2.]
x // y :  [2 2 2 2 2]
x ** y :  [     2     16    216   4096 100000]


## 3) Indexing and Slicing

In [8]:
# Indexing : Select certain elements
x = np.arange(-5,5)
print("x : ",x)

print("x[2] : ",x[2])

y = x[3:5]     # y is a slice, i.e., pointer to a subarray in x
print("y : ",y)
y[:] = 1000    # modifying the value of y will change x
print("y : ",y)
print("x : ",x)

z = x[3:5].copy()   # makes a copy of the subarray
print("z : ",z)
z[:] = 500          # modifying the value of z will not affect x
print("z : ",z)
print("x : ",x)

x :  [-5 -4 -3 -2 -1  0  1  2  3  4]
x[2] :  -3
y :  [-2 -1]
y :  [1000 1000]
x :  [  -5   -4   -3 1000 1000    0    1    2    3    4]
z :  [1000 1000]
z :  [500 500]
x :  [  -5   -4   -3 1000 1000    0    1    2    3    4]


In [9]:
my2dlist = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]   # a 2-dim list
print("my2dlist       : ",my2dlist)
print("my2dlist[2]    : ",my2dlist[2])        # access the third sublist
print("my2dlist[:][2] : ",my2dlist[:][2])     # can't access third element of each sublist
#print(my2dlist[:,2])    # this will cause syntax error

my2darr = np.array(my2dlist)
print("my2darr       : ",my2darr)
print("my2darr[2][:] : ",my2darr[2][:])      # access the third row
print("my2darr[2,:]  : ",my2darr[2,:])       # access the third row
print("my2darr[:][2] : ",my2darr[:][2])      # access the third row (similar to 2d list)
print("my2darr[:,2]  : ",my2darr[:,2])       # access the third column
print("my2darr[:2,2:]: ",my2darr[:2,2:])     # access the first two rows & last two columns

my2dlist       :  [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
my2dlist[2]    :  [9, 10, 11, 12]
my2dlist[:][2] :  [9, 10, 11, 12]
my2darr       :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
my2darr[2][:] :  [ 9 10 11 12]
my2darr[2,:]  :  [ 9 10 11 12]
my2darr[:][2] :  [ 9 10 11 12]
my2darr[:,2]  :  [ 3  7 11]
my2darr[:2,2:]:  [[3 4]
 [7 8]]


In [10]:
my2darr = np.arange(1,13,1).reshape(3,4)
print("my2darr : ",my2darr)

divBy3 = my2darr[my2darr % 3 == 0]
print("divBy3        : ",divBy3)
print("type(divBy3)  : ",type(divBy3))

divBy3LastRow = my2darr[2:, my2darr[2,:] % 3 == 0]
print("divBy3LastRow : ",divBy3LastRow)

my2darr :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
divBy3        :  [ 3  6  9 12]
type(divBy3)  :  <class 'numpy.ndarray'>
divBy3LastRow :  [[ 9 12]]


In [11]:
my2darr = np.arange(1,13,1).reshape(4,3)
print("my2darr : ",my2darr)

indices = [2,1,0,3]    # selected row indices
print("my2darr[indices,:] : ",my2darr[indices,:])

rowIndex = [0,0,1,2,3]     # row index into my2darr
columnIndex = [0,2,0,1,2]  # column index into my2darr
print("my2darr[rowIndex,columnIndex]) : ",my2darr[rowIndex,columnIndex])

my2darr :  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
my2darr[indices,:] :  [[ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]
 [10 11 12]]
my2darr[rowIndex,columnIndex]) :  [ 1  3  4  8 12]


## 4) Arithmetic and Statistical Functions

In [12]:
# Build-in mathematical functions
y = np.array([-1.4, 0.4, -3.2, 2.5, 3.4])    # generate a random vector
print("y : ",y)

print("np.abs(y)       : ",np.abs(y))          # convert to absolute values
print("np.sqrt(abs(y)) : ",np.sqrt(abs(y)))    # apply square root to each element
print("np.sign(y)      : ",np.sign(y))         # get the sign of each element
print("np.exp(y)       : ",np.exp(y))          # apply exponentiation
print("np.sort(y)      : ",np.sort(y))         # sort array

y :  [-1.4  0.4 -3.2  2.5  3.4]
np.abs(y)       :  [1.4 0.4 3.2 2.5 3.4]
np.sqrt(abs(y)) :  [1.18321596 0.63245553 1.78885438 1.58113883 1.84390889]
np.sign(y)      :  [-1.  1. -1.  1.  1.]
np.exp(y)       :  [ 0.24659696  1.4918247   0.0407622  12.18249396 29.96410005]
np.sort(y)      :  [-3.2 -1.4  0.4  2.5  3.4]


In [13]:
x = np.arange(-2,3)
y = np.random.randn(5)
print("x : ",x)
print("y : ",y)

print("np.add(x,y) : ",np.add(x,y))           # element-wise addition       x + y
print("np.subtract(x,y) : ",np.subtract(x,y))      # element-wise subtraction    x - y
print("np.multiply(x,y) : ",np.multiply(x,y))      # element-wise multiplication x * y
print("np.divide(x,y)   : ",np.divide(x,y))        # element-wise division       x / y
print("np.maximum(x,y)  : ",np.maximum(x,y))       # element-wise maximum        max(x,y)

x :  [-2 -1  0  1  2]
y :  [0.66664429 0.39258355 2.42049717 1.13333213 0.3926671 ]
np.add(x,y) :  [-1.33335571 -0.60741645  2.42049717  2.13333213  2.3926671 ]
np.subtract(x,y) :  [-2.66664429 -1.39258355 -2.42049717 -0.13333213  1.6073329 ]
np.multiply(x,y) :  [-1.33328858 -0.39258355  0.          1.13333213  0.78533421]
np.divide(x,y)   :  [-3.0001007  -2.54722845  0.          0.88235387  5.09337293]
np.maximum(x,y)  :  [0.66664429 0.39258355 2.42049717 1.13333213 2.        ]


In [14]:
y = np.array([-3.2, -1.4, 0.4, 2.5, 3.4])    # generate a random vector
print("y : ",y)

print("Min =", np.min(y))             # min 
print("Max =", np.max(y))             # max 
print("Average =", np.mean(y))        # mean/average
print("Std deviation =", np.std(y))   # standard deviation
print("Sum =", np.sum(y))             # sum 

y :  [-3.2 -1.4  0.4  2.5  3.4]
Min = -3.2
Max = 3.4
Average = 0.34000000000000014
Std deviation = 2.432776191925595
Sum = 1.7000000000000006


## 5) Linear algebra

In [15]:
# Linear algebra function
X = np.random.randn(2,3)    # create a 2 x 3 random matrix
print("X   : ",X)
print("X.T : ",X.T)             # matrix transpose operation X^T

y = np.random.randn(3) # random vector 
print("y : ",y)
print("X.dot(y)   : ",X.dot(y))        # matrix-vector multiplication  X * y
print("X.dot(X.T) : ",X.dot(X.T))      # matrix-matrix multiplication  X * X^T
print("X.T.dot(X) : ",X.T.dot(X))      # matrix-matrix multiplication  X^T * X

X   :  [[ 0.11319849 -0.61061896 -0.26512575]
 [ 0.45350864  1.15835945  2.42153558]]
X.T :  [[ 0.11319849  0.45350864]
 [-0.61061896  1.15835945]
 [-0.26512575  2.42153558]]
y :  [-0.1397508   1.01982356  2.22548579]
X.dot(y)   :  [-1.22857677  6.50703709]
X.dot(X.T) :  [[ 0.45596107 -1.2979912 ]
 [-1.2979912   7.41130129]]
X.T.dot(X) :  [[0.21848398 0.45620487 1.06817546]
 [0.45620487 1.71465213 2.96689944]
 [1.06817546 2.96689944 5.93412625]]


In [16]:
X = np.random.randn(5,3)
print("X : ",X)

C = X.T.dot(X)               # C = X^T * X is a square matrix

invC = np.linalg.inv(C)      # inverse of a square matrix
print("invC : ",invC)
detC = np.linalg.det(C)      # determinant of a square matrix
print("detC : ",detC)
S, U = np.linalg.eig(C)      # eigenvalue S and eigenvector U of a square matrix
print("S : ",S)
print("U : ",U)

X :  [[-0.80409246 -2.01111405  2.30567736]
 [ 0.17630872  0.64430778 -1.33869202]
 [ 1.06303628  0.70849799  0.07299663]
 [-0.38223768 -0.1315711   0.1738208 ]
 [-0.84962649  1.42726764 -2.24743419]]
invC :  [[ 1.04546244 -1.49446577 -1.04901199]
 [-1.49446577  3.3265487   2.34657191]
 [-1.04901199  2.34657191  1.73736376]]
detC :  9.80006417332046
S :  [ 2.99635682  0.17475783 18.71538427]
U :  [[ 0.9297336   0.3636709  -0.05778332]
 [ 0.25914317 -0.75767647 -0.59897512]
 [ 0.26161088 -0.54191314  0.7986801 ]]


## 6) Broadcasting

In [17]:
import numpy as np
A = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
B = np.array([[0,1,2],[0,1,2],[0,1,2],[0,1,2]])
print("A : \n", A)
print(str("Shape of A = ")+str(A.shape))
print("B : \n", B)
print(str("Shape of B = ")+str(B.shape))
print("A+B : \n", A+B)
print(str("Shape of A + B = ")+str((A+B).shape))

A : 
 [[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
Shape of A = (4, 3)
B : 
 [[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]
Shape of B = (4, 3)
A+B : 
 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
Shape of A + B = (4, 3)


In [18]:
import numpy as np
A = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
B = np.array([0,1,2])
print("A : \n", A)
print(str("Shape of A = ")+str(A.shape))
print("B : \n", B)
print(str("Shape of B = ")+str(B.shape))
print("A+B : \n", A+B)
print(str("Shape of A + B = ")+str((A+B).shape))

A : 
 [[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
Shape of A = (4, 3)
B : 
 [0 1 2]
Shape of B = (3,)
A+B : 
 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
Shape of A + B = (4, 3)


In [19]:
import numpy as np
A = np.array([[0],[10],[20],[30]])
B = np.array([0,1,2])
print("A : \n", A)
print(str("Shape of A = ")+str(A.shape))
print("B : \n", B)
print(str("Shape of B = ")+str(B.shape))
print("A+B : \n", A+B)
print(str("Shape of A + B = ")+str((A+B).shape))

A : 
 [[ 0]
 [10]
 [20]
 [30]]
Shape of A = (4, 1)
B : 
 [0 1 2]
Shape of B = (3,)
A+B : 
 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
Shape of A + B = (4, 3)


## สรุปเนื้อหา

1. Numpy Array : np.array([1.0,2,3,4,5])

2. Element-wise Operations : +, -, *, /, //, **, %

3. Indexing and Slicing : x[3], x[3:5]

4. Arithmetic and Statistical : np.abs(x), np.sqrt(x), np.sign(x), np.exp(x), np.sort(x), np.add(x,y), np.subtract(x,y), np.multiply(x,y), np.divide(x,y), np.maximum(x,y), np.min(x), np.max(x),np.mean(), np.std(x), np.sum(x)

5. Linear Algebra : X.T, X.dot(x), np.linalg.inv(x), np.linalg.det(x), np.linalg.eig(x)

6. Broadcasting